### ISSUE TITLE
cannot configure

### ISSUE THREAD

**Issue by amerello** [Rostlab/LocTree#2]
executing _./configure_ produces the following error:
`config.status: error: cannot find input file: 'data/Makefile.in'`
executing _make_ afterwards fails.

**Comment by juanmirocks** [comment]
Great. These kind of errors are the ones we want to solve. Note that for next week (Nov 5) is sufficient to move the repo to git with the history (what you already did) and list in the README.md some key points of the tool. See: https://github.com/Rostlab/PP2_CS_WS_2015-16/issues/1

Specifically for this issue, it seems that no `Makefile.in` exists, but `Makefile.am` (https://github.com/Rostlab/LocTree/tree/master/data)

**Comment by juanmirocks** [comment]
@gyachdav maybe you know ?

**Comment by gyachdav** [comment]
The repo indeed doesn't have the makefile.in. Note that this file  should not be versioned in the repo as it is only relevant for build time and not part of the code base. 

In order to generate this file and build the tar.gz archive for this package you should take a look at 

https://rostlab.org/owiki/index.php/Packaging_howto#automake_and_autoconf

and esp follow the steps described at the end of the section. [Make sure you understand what each command does and don't just blindly run them sequentially. ]

**Comment by juanmirocks** [comment]
@gyachdav but I think think the file is still relevant to have and be able to move around. I guess it can be separated from the actual source code, either in a separate folder or root folder.

That's the norm for say .pom or npm build files.

**Comment by gyachdav** [comment]
There's no reason to keep this file in the repo as it will get rebuilt every time you make a package. Since this is a target machine specific build file keeping it and trying to reuse it on a different system could result in a messed up build process.

**Comment by juanmirocks** [comment]
@gyachdav OK got it. Agree.

**Comment by amerello** [comment]
This problem is solved. Relevant information has been added to README.md
